---
language: php

addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.3
- 7.2
- 7.1
- 7.0

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.3
  - php: 7.0

before_install:
- go get -u github.com/jingweno/ccat
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi

install:
- composer install

script:
- php -S 127.0.0.1:8000 -t public &>/dev/null & printf 'HEAD /admin/dashboard HTTP/1.1\r\n\r\n' | socat - TCP4:localhost:8000,forever >/dev/null # Waiting for server to connect.
- elinks http://localhost:8000/admin/dashboard -dump-color-mode 4 -dump

after_script:
- ls --color

- composer show --latest
- $GOPATH/bin/ccat composer.json

- composer require --no-scripts sensiolabs/security-checker
- composer security:check -- --end-point=http://security.sensiolabs.org/check_lock --ansi
- $GOPATH/bin/ccat composer.json
